## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "catppuccin_mocha"

# Setups
format = '''
$directory $git_branch $git_state $git_metrics $nodejs$rust
> '''
# add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
java.disabled = true
golang.disabled = true

[directory]
format = "($style)[$path]($style)"
style = "fg:green"
truncation_length = 3
truncate_to_repo = false
read_only = '🔒'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_branch]
format = "[($style)$symbol$branch]($style)"
style = "fg:blue"
symbol = "✦ "
truncation_length = 10

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[nodejs]
disabled = false
format = "▲ $version"

# ~/.config/starship.toml

[rust]
disabled = false
symbol = "🦀"
format = 'via [$symbol $version](red bold)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#F5BDE6"
mauve = "#cba6f7"
red = "#ED8796"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#EED49F"
green = "#A6DA95"
teal = "#8BD5CA"
sky = "#8AADF4"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#B8C0E0"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#494D64"
mantle = "#181825"
crust = "#11111b"
